Long api code attached email
oda-hub/dispatcher-app pull request #270
Opened 2021-10-29 16:38 UTC by burnout87

2021-11-01 09:57 UTC, volodymyrss commented
I will look on it when possible. To be clear, we can not really deploy it before [hotfixes](https://github.com/issues?q=is%3Aopen+archived%3Afalse++org%3Aoda-hub+label%3Ahotfix) are implemented. So while it is possible to merge it before, it may delay hotfix.

2021-11-01 10:00 UTC, burnout87 commented
> I will look on it when possible. To be clear, we can not really deploy it before [hotfixes](https://github.com/issues?q=is%3Aopen+archived%3Afalse++org%3Aoda-hub+label%3Ahotfix) are implemented. So while it is possible to merge it before, it may delay hotfix.

I will convert it back to draft. Since changes that we apply with the hotfixes might have an impact here.

2021-11-05 09:14 UTC, volodymyrss commented on cdci_data_analysis/analysis/email_helper.py
> +                                             filename="api code")
```suggestion
filename="api_code.py")
```

2021-11-05 09:20 UTC, volodymyrss commented on cdci_data_analysis/flask_app/templates/email.html
> +However, a python script with the api code has been attached to this email.
It's not really that problematic anymore. Just less favorable. Also I do not think we get an alert?

```suggestion
Please note the API code for this query was too large to embed it in the email text. Instead, we attach it as a python script.
```

2021-11-05 09:21 UTC, volodymyrss commented on tests/test_job_management.py
> +ignore_api_code_patterns = [
maybe `api_attachment_attachment_patterns` or something like that

2021-11-05 10:46 UTC, volodymyrss requested changes
Small comments

2021-11-05 13:35 UTC, volodymyrss approved these changes

2021-11-05 13:41 UTC, merged