Refer to https://github.com/oda-hub/doc-multi-user/
oda-hub/dispatcher-app pull request #44
Opened 2021-03-31 14:15 UTC by ferrigno

I added references in interface.md to the other documents defining user fields and roles.
I think it is relevant to understand how we want to manage users. The possibility of multiple sources of identification could carry a degree of issues with the interface definition.

2021-03-31 14:29 UTC, volodymyrss requested changes

2021-03-31 14:29 UTC, volodymyrss commented on interfaces.md
> +See [the roles](https://github.com/oda-hub/doc-multi-user/blob/CF_proposal/plan-roles-users.md)
this link will vanish too. plan-roles-user.md already exists, we can refer to that already

2021-03-31 14:29 UTC, volodymyrss commented on interfaces.md
> +Users are generated in the Drupal web interface, reuired fields are in [the note](https://github.com/oda-hub/doc-multi-user/blob/CF_proposal/user-fields.md)
I would say users are  defined, though generated is fine if you prefer.
The reference to PR branch will go away, so maybe we can directly use that.

2021-03-31 14:54 UTC, volodymyrss commented
could you please not merge things if review is incpmplete

2021-03-31 14:55 UTC, volodymyrss commented
if you have happy with your update you  can re-request review there is a button there near review.

2021-03-31 14:55 UTC, ferrigno commented
Just made a mistake on using github interface, sorry.

2021-03-31 14:57 UTC, volodymyrss commented
review is not just or even necessarily for approval, is for keeping track. unreviewed changes are disruptive, since they will not be appreciated, and will introduce confusion.
even if in this case it is clear that the is no misunderstanding, let's follow a practice?

2021-03-31 15:04 UTC, ferrigno commented
I agree that awareness of mutual contributions is fundamental, but it is just not clear to me at which point something can be closed and merged, I thought that implementing your comments was sufficient to "close with comment". However, it looks that this did not actually merged the branch, which, by the way, should be deleted after merging, I think. I leave the final action to you.

2021-03-31 15:09 UTC, volodymyrss commented
> I agree that awareness of mutual contributions is fundamental, but it is just not clear to me at which point something can be closed and merged, I thought that implementing your comments was sufficient to "close with comment". However, it looks that this did not actually merged the branch, which, by the way, should be deleted after merging, I think. I leave the final action to you.

ok, it's a technical aspect. at the same top right corner where you put reviewers, you can "re-request" review, there is button. 
then they will be converted to pending (mine is currently in "changes requested" and @burnout87 's is "pending").

it also says in big red letters just above here "Changes requested".

once both reviews are approched, they convert to green tick marks, and other comments become all green.
then we can merge. I'd say anyone can merge at that point, but usually it's natural it's the original submitter. 
in this case, we can complete ourselves, since really the content is small. but it's just to agree on the workflow (in this case it is standard github PR workflow)

2021-04-01 11:05 UTC, volodymyrss approved these changes

2021-04-01 11:06 UTC, volodymyrss commented
I made non-negligible changes to this, but I can not assign @ferrigno to review since he created it. So I wait for @burnout87  review or further comments from @ferrigno and merge. Further changes are possible after.

2021-04-01 11:56 UTC, burnout87 commented on interfaces.md
> +Meaning of Roles and Source of Roles definition are described below.
Good, I like this explanation, very clear.

2021-04-01 15:05 UTC, merged

2021-04-01 15:06 UTC, volodymyrss commented
Oh, sorry @burnout87 turns out your review was not approved. The comments indicated so, so I merged, my bad. 
Is it ok? Else we try to revert.

2021-04-01 15:11 UTC, burnout87 commented
It's ok no problem. It was more of a curiosity for me. Things that will anyway become clear soon

2021-04-01 15:17 UTC, volodymyrss commented
> It's ok no problem. It was more of a curiosity for me. Things that will anyway become clear soon

it's also so that you acknowledge you are aware of these changes and this doc. It would be a shame if you missed it!

2021-04-01 15:18 UTC, burnout87 commented
Indeed, but I saw them all and commented where I wantend to