including os library
oda-hub/dispatcher-app pull request #480
Opened 2022-12-06 14:10 UTC by burnout87

2022-12-06 14:20 UTC, volodymyrss approved these changes

2022-12-06 15:50 UTC, burnout87 commented
> Will address also #481

It checks if the branch already exists in the remote, if so, makes a git pull so to avoid the error when pushing to the branch, and also avoid to force push

2022-12-06 16:06 UTC, volodymyrss commented
> > Will address also #481
> 
> It checks if the branch already exists in the remote, if so, makes a git pull so to avoid the error when pushing to the branch, and also avoid to force push

Usually, there should be no need to commit anything, right? 
The commit is only needed when new version of the code is generated.
In such a case, the branch will also contain previous version of the code. It's not really useful for the user and may cause confusion.
We want this live session to be potentially directly used for developing added-value workflow.

So I'd suggest to add in the branch name the version of the code. Actually, you can just use hash of the notebook content.

We can also keep to pull-and-commit behavior you add now as a fallback if something unexpected happens. We should also send a sentry alert in this case.

2022-12-06 16:17 UTC, burnout87 commented
addressing also #478

2022-12-06 20:53 UTC, burnout87 commented
> 
> Usually, there should be no need to commit anything, right? The commit is only needed when new version of the code is generated. In such a case, the branch will also contain previous version of the code. It's not really useful for the user and may cause confusion. We want this live session to be potentially directly used for developing added-value workflow.
> 

Yes this is true. Indeed now, it pulls in case the branch already exists, and get the commit hex, that uses to generate the url.
If the branch does not exists, it makes the push.


> So I'd suggest to add in the branch name the version of the code. Actually, you can just use hash of the notebook content.
> 
I generate a has using the content of the notebook. I had to remove two fieds, two ids, that were generate at the moment the notebook object was created.

> We can also keep to pull-and-commit behavior you add now as a fallback if something unexpected happens. We should also send a sentry alert in this case.

As of now. it sends a sentry in case something goes wrong, let's if it is enough

2022-12-07 11:45 UTC, volodymyrss commented on cdci_data_analysis/analysis/renku_helper.py
> +    return file_path
some new lines here

2022-12-07 11:47 UTC, volodymyrss requested changes
just some formatting point

2022-12-07 15:36 UTC, volodymyrss approved these changes

2022-12-07 16:03 UTC, merged