inclusive bounds
oda-hub/dispatcher-app pull request #508
Opened 2023-01-18 14:14 UTC by dsavchenko

2023-01-18 16:41 UTC, dsavchenko commented
Also fix for the bug we encountered on our live testing

2023-01-19 12:05 UTC, burnout87 requested changes

2023-01-19 12:12 UTC, dsavchenko commented on cdci_data_analysis/analysis/parameters.py
>                  raise RequestNotUnderstood(f'Parameter {name} wrong value {val}: should be lower than {max_value}')
But no, these are conditions to raise errors, so that it passes for val=min_value, val=max_value

2023-01-19 12:14 UTC, burnout87 commented on cdci_data_analysis/analysis/parameters.py
>                  raise RequestNotUnderstood(f'Parameter {name} wrong value {val}: should be lower than {max_value}')
I am talking of the message within the raised exception

2023-01-19 13:12 UTC, burnout87 approved these changes

2023-01-19 14:33 UTC, volodymyrss approved these changes

2023-01-19 15:43 UTC, dsavchenko commented
merge it please

2023-01-19 15:44 UTC, merged