prod_name in get_par_by_name
oda-hub/dispatcher-app pull request #537
Opened 2023-05-12 09:40 UTC by dsavchenko

2023-05-12 09:42 UTC, volodymyrss commented on cdci_data_analysis/analysis/instrument.py
> +    def get_par_by_name(self,par_name,add_src_query=True,add_instr_query=True,prod_name=None):
space after coma?

2023-05-12 09:43 UTC, volodymyrss commented
it seems to make sense, but could you please explain a little bit the motivation?

2023-05-12 10:01 UTC, dsavchenko commented
> it seems to make sense, but could you please explain a little bit the motivation?

I came up with this in the context of https://github.com/oda-hub/dispatcher-plugin-nb2workflow/issues/47. When I build a request to the backend, I want to be sure that the parameter I'm working with is coming from the proper product. If parameters with the same name are annotated differently in the notebooks, they are not equivalent in the dispatcher. It addresses the TODO comment https://github.com/oda-hub/dispatcher-app/blob/439af5dc3a94c7d328f46445b0e464de6b1fdd60/cdci_data_analysis/analysis/instrument.py#L524 for this case.

It's not a strictly necessary change, I guess, as the problem in https://github.com/oda-hub/dispatcher-plugin-nb2workflow/issues/47 concerns SourceQuery parameters, but it's cleaner to use it this way

2023-05-12 10:06 UTC, volodymyrss approved these changes

2023-05-12 10:06 UTC, volodymyrss commented
something breaks though

2023-05-12 10:07 UTC, volodymyrss commented
oh, do we already have test for this? could you add one?

2023-05-12 10:42 UTC, burnout87 requested changes
Very useful thanks

2023-05-12 10:42 UTC, burnout87 commented on cdci_data_analysis/analysis/instrument.py
> +            if isinstance(_query, SourceQuery) and add_src_query==False:
```suggestion
            if isinstance(_query, SourceQuery) and not add_src_query:
```

2023-05-12 10:42 UTC, burnout87 commented on cdci_data_analysis/analysis/instrument.py
> +            if isinstance(_query, InstrumentQuery) and add_instr_query==False:
```suggestion
            if isinstance(_query, InstrumentQuery) and not add_instr_query:
```

2023-05-12 10:42 UTC, burnout87 commented on cdci_data_analysis/analysis/instrument.py
> +            if isinstance(_query, SourceQuery) and add_src_query==False:
```suggestion
            if isinstance(_query, SourceQuery) and not add_src_query:
```

2023-05-14 17:18 UTC, burnout87 approved these changes

2023-05-15 12:44 UTC, volodymyrss approved these changes

2023-05-21 10:32 UTC, dsavchenko commented
could you merge please?

2023-05-21 10:37 UTC, volodymyrss commented
I add you to maintainers, I think you add enough code. I merge though

2023-05-21 10:38 UTC, merged