return_progress as arg for run_query
oda-hub/dispatcher-app pull request #601
Opened 2023-10-11 16:34 UTC by burnout87

2023-10-12 08:44 UTC, burnout87 commented
An additional boolean argument for the `run_analysis` endpoint is extracted: `return_progress`, and this is passed, as argument to `run_query` of the instrument and in turn to the `run_query` of the query object requested.

In this way, each plugin can behave differently if the return_progress is passed as True.

Is this what you had in mind @volodymyrss  ?

2023-10-12 08:51 UTC, volodymyrss commented
something like that, we need to try interface with test plugin, and of course preserve existing behavior

2023-10-17 15:09 UTC, burnout87 commented
Adding the arg `return_progress` to the `run_query` and `get_dummy_products` functions of a `data_server_query` breaks the existing behavior of all the plugins

2023-10-25 20:30 UTC, burnout87 commented
* `return_progress` is now an arg for the `run_analysis` endpoint, and it is used within the `run_query` function
* it is used to extract the current status of a product
* `ReturnProgressProductQuery` is a dummy Product that simply reads the content of a file and returns it after some simple mathematical processing
* `ReturnProgressDataServerQuery` is a dummy daserver that behaves identically to `ReturnProgressProductQuery`

2023-10-31 12:49 UTC, dsavchenko commented
Could you please also add a test for the real (non-dummy) requests? 
I'm not sure, I properly understand the intended logic. In dummy progress query you return the same product as in simple dummy query. But here https://github.com/oda-hub/dispatcher-app/blob/d954c556aff40b320c866d5d79be284990bb2ee8/cdci_data_analysis/plugins/dummy_plugin/data_server_dispatcher.py#L180 there is no product, but some messages are set instead.

2023-10-31 13:55 UTC, burnout87 commented
> Could you please also add a test for the real (non-dummy) requests? 

Yes, I will add the test.

> I'm not sure, I properly understand the intended logic. In dummy progress query you return the same product as in simple dummy query. But here
> 
> https://github.com/oda-hub/dispatcher-app/blob/d954c556aff40b320c866d5d79be284990bb2ee8/cdci_data_analysis/plugins/dummy_plugin/data_server_dispatcher.py#L180
> there is no product, but some messages are set instead.

Good point, I will adjust it so that it returns the product. That will actually be built afterwards within the `build_product_list`

2023-10-31 17:35 UTC, burnout87 commented
> Could you please also add a test for the real (non-dummy) requests? I'm not sure, I properly understand the intended logic. In dummy progress query you return the same product as in simple dummy query. But here
> 
> https://github.com/oda-hub/dispatcher-app/blob/d954c556aff40b320c866d5d79be284990bb2ee8/cdci_data_analysis/plugins/dummy_plugin/data_server_dispatcher.py#L180
> there is no product, but some messages are set instead.

test added, and applied some more  logic, I think it makes more sense now

2023-11-01 11:20 UTC, dsavchenko submitted a review, later dismissed

2023-11-03 10:45 UTC, dsavchenko commented
So there are two failures in "test oda_api". One is expected, as it doesn't include the new dummy instrument, but there is also `FAILED tests/test_live.py::test_instruments - oda_api.api.UnexpectedDispatcherStatusCode: UnexpectedDispatcherStatusCode (line 98): status: 403, raw: The token provided is not valid.` do you know why does it fail here?

2023-11-03 10:54 UTC, burnout87 commented
> So there are two failures in "test oda_api". One is expected, as it doesn't include the new dummy instrument, but there is also `FAILED tests/test_live.py::test_instruments - oda_api.api.UnexpectedDispatcherStatusCode: UnexpectedDispatcherStatusCode (line 98): status: 403, raw: The token provided is not valid.` do you know why does it fail here?

About the second I actually don't know. As for the first I verified that it is the case of just the missing dummy instrument: https://github.com/oda-hub/oda_api/pull/224

2023-11-03 14:28 UTC, burnout87 commented
> 
> EDIT it really looks like an expired token is used, unclear the reason why

The "funny" thing is that when the token is discovered, it is not expired, but afterwards, the error I see is `ExpiredSignatureError`

2023-11-08 16:49 UTC, volodymyrss approved these changes

2023-11-08 17:24 UTC, burnout87 commented
I keep seeing this error from the oda_api run:

`tests/test_live.py::test_instruments - oda_api.api.UnexpectedDispatcherStatusCode: UnexpectedDispatcherStatusCode (line 98): status: 403, raw: The token provided is not valid.`

I investigated a lot but still it is to me completely unclear why it  happens

2023-11-09 08:45 UTC, burnout87 commented
> I keep seeing this error from the oda_api run:
> 
> `tests/test_live.py::test_instruments - oda_api.api.UnexpectedDispatcherStatusCode: UnexpectedDispatcherStatusCode (line 98): status: 403, raw: The token provided is not valid.`
> 
> I investigated a lot but still it is to me completely unclear why it happens

By checking out a specific branch from the `oda_api` (https://github.com/oda-hub/oda_api/pull/224) , fixed the problem, and I dont really get why, since the test that was failing was one not dealing with the new dummy instrument (actually no dummy instrument was touched by it, supposedly)

2023-11-09 09:49 UTC, volodymyrss commented
> I keep seeing this error from the oda_api run:
> 
> `tests/test_live.py::test_instruments - oda_api.api.UnexpectedDispatcherStatusCode: UnexpectedDispatcherStatusCode (line 98): status: 403, raw: The token provided is not valid.`
> 
> I investigated a lot but still it is to me completely unclear why it happens

Could you maybe add more logging to enable this?

2023-11-09 16:39 UTC, burnout87 commented
> > I keep seeing this error from the oda_api run:
> > `tests/test_live.py::test_instruments - oda_api.api.UnexpectedDispatcherStatusCode: UnexpectedDispatcherStatusCode (line 98): status: 403, raw: The token provided is not valid.`
> > I investigated a lot but still it is to me completely unclear why it happens
> 
> By checking out a specific branch from the `oda_api` ([oda-hub/oda_api#224](https://github.com/oda-hub/oda_api/pull/224)) , fixed the problem, and I dont really get why, since the test that was failing was one not dealing with the new dummy instrument (actually no dummy instrument was touched by it, supposedly)

I think I have it figured out, finally.

When running the `oda_api` tests, the first test failing is `test_cli.py::test_get`, and it's expected.

The other test to fail is `test_live.py::test_instruments` which sends a request to the production instance with an invalid token.

This invalid token is discovered within the environment by the oda_api, and then sent to the production dispatcher, which, obviously fails, since the token is not valid (it is signed with the test secret key).

The tests run before `test_instruments` (tests within `test_cli`, in particular `test_token_modify` and  `test_token_inspect`), leave some token within the local environment (env_var and current directory) that are then used within the context of `test_instruments`, making it fail for invalid token.

A dedicated PR will address this

2023-11-09 16:48 UTC, dsavchenko commented
But why have this error appeared in this PR only?

2023-11-09 16:50 UTC, volodymyrss commented
> But why have this error appeared in this PR only?

maybe the order of tests is changing?.. it's not guaranteed to be always the same.

2023-11-09 16:51 UTC, volodymyrss commented
> > > I keep seeing this error from the oda_api run:
> > > `tests/test_live.py::test_instruments - oda_api.api.UnexpectedDispatcherStatusCode: UnexpectedDispatcherStatusCode (line 98): status: 403, raw: The token provided is not valid.`
> > > I investigated a lot but still it is to me completely unclear why it happens
> > 
> > 
> > By checking out a specific branch from the `oda_api` ([oda-hub/oda_api#224](https://github.com/oda-hub/oda_api/pull/224)) , fixed the problem, and I dont really get why, since the test that was failing was one not dealing with the new dummy instrument (actually no dummy instrument was touched by it, supposedly)
> 
> I think I have it figured out, finally.
> 
> When running the `oda_api` tests, the first test failing is `test_cli.py::test_get`, and it's expected.
> 
> The other test to fail is `test_live.py::test_instruments` which sends a request to the production instance with an invalid token.
> 
> This invalid token is discovered within the environment by the oda_api, and then sent to the production dispatcher, which, obviously fails, since it is signed with the test secret key.
> 
> The tests run before `test_instruments` and `test_get` (tests within `test_cli`, in particular `test_token_modify` and `test_token_inspect`), leave some token within the local environment (env_var and current directory) that are then used within the context of `test_instruments`, making it fail for invalid token.
> 
> A dedicated PR will address this

interesting! Indeed, each test env variables should be strickly controlled, all set before the test.

2023-11-09 16:56 UTC, burnout87 commented
> But why have this error appeared in this PR only?

`test_token_modify` and `test_token_inspect` run before `test_get` and do not clean-up the tokens they generate.

The test `test_get`  does some token clean-up, but in this instance it fails (without completing of course) because of the missing new dummy instrument that is introduced with this PR (as expected).

But the clean-up does not happen and therefore `test_instruments` fails.

2023-11-09 16:56 UTC, burnout87 commented
> 
> interesting! Indeed, each test env variables should be strickly controlled, all set before the test.

It took quite some debugging...and a bit of imagination

2023-11-09 16:58 UTC, burnout87 commented
> > But why have this error appeared in this PR only?
> 
> maybe the order of tests is changing?.. it's not guaranteed to be always the same.

exactly, I discovered because I made the assumption that such order was followed...but just in this instance. it's not always like that

2023-11-09 17:09 UTC, volodymyrss commented
> > But why have this error appeared in this PR only?
> 
> `test_token_modify` and `test_token_inspect` run before `test_get` and do not clean-up the tokens they generate.
> 
> The test `test_get` does some token clean-up, but in this instance it fails (without completing of course) because of the missing new dummy instrument that is introduced with this PR (as expected).
> 
> But the clean-up does not happen and therefore `test_instruments` fails.

It's best to never rely on tests to clean-up anything. Instead, clean environment should be created before the test.

2023-11-09 17:09 UTC, volodymyrss commented
> > > But why have this error appeared in this PR only?
> > 
> > 
> > maybe the order of tests is changing?.. it's not guaranteed to be always the same.
> 
> exactly, I discovered because I made the assumption that such order was followed...but just in this instance. it's not always like that

tests can even be run in parallel, so no way to guarantee order.

2023-11-13 09:19 UTC, volodymyrss commented on cdci_data_analysis/analysis/queries.py
> +                        prod_list = self.build_product_list(instrument,res, scratch_dir,api=api)
this line duplicates the one just above

2023-11-17 13:58 UTC, volodymyrss requested changes
test fails

2023-11-17 15:10 UTC, burnout87 commented
> test fails

The test `est_cli.py::test_get` from the `oda_api` fails becaus an adaptation is needed by adding the dummy instrument introduced here, but with https://github.com/oda-hub/oda_api/pull/224 this will be fixed (I have verified that the tests pass by checking out that specific `oda_api` branch)

2023-11-17 15:32 UTC, volodymyrss commented
> > test fails
> 
> The test `est_cli.py::test_get` from the `oda_api` fails becaus an adaptation is needed by adding the dummy instrument introduced here, but with [oda-hub/oda_api#224](https://github.com/oda-hub/oda_api/pull/224) this will be fixed (I have verified that the tests pass by checking out that specific `oda_api` branch)

right, well, this PR will wait for the fix then.

2023-11-20 16:05 UTC, burnout87 commented
tests passing now

2023-11-20 16:41 UTC, merged